'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dashboard

    '''<summary>
    '''divAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divConvenor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConvenor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSupervisor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStudent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divPM_taskAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPM_taskAccept As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''divRegisteredUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRegisteredUnit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divUnitConv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnitConv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvConvenor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvConvenor As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divUnitSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnitSup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSupervisor As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divUnitStu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnitStu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStudent As Global.System.Web.UI.WebControls.GridView
End Class
